; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!


#define MyAppName "DevisMHU"
#define MyAppVersion "20.9.3.0"
#define MyAppPublisher "MHU"
#define MyAppURL "http://www.mhu.fr"
#define MyAppExeName "devismhu.exe"
#define Mysetupname "majdevis_20-9-3-0"
#define MyOption ""


[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
PrivilegesRequired=lowest
AppId={{57F88F2A-3F84-4557-9868-4C65114B22D1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=c:\mhu

DisableDirPage=yes
DefaultGroupName=mhu
DisableProgramGroupPage=yes
WizardStyle=modern
DisableWelcomePage=no
OutputDir=C:\devissetup
OutputBaseFilename={#Mysetupname}{#MyOption}
SetupIconFile=C:\devissetup\caisse.ico
Compression=lzma
SolidCompression=yes
WizardImageFile=c:\devissetup\imgsetup.bmp
WizardSmallImageFile=c:\devissetup\logomhu55.bmp

[Languages]
Name: "fr"; MessagesFile: "compiler:Languages\French.isl"

[Messages]
WelcomeLabel2= Cet assistant va procéder à la mise à jour de [name/ver] {#MyOption} sur votre ordinateur.

[Code]
procedure InitializeWizard();
begin
  WizardForm.WelcomeLabel2.Font.Style := [fsBold]; //Bold
  WizardForm.WelcomeLabel2.Font.Color := clnavy; // And red colour
end;

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";


[Dirs]
Name: "{app}\devis"
Name: "{app}\offre"
Name: "{app}\log"
Name: "{app}\exportdevis"

[Files]

Source: "C:\deviscim\Win32\Release\devismhu.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\devismaint\Win32\Release\maintdevis.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\deviscim\Win32\Release\alerteheure.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\devissetup\*.dll"; DestDir: "{app}"; Flags: ignoreversion 

; Suite que si modif

Source: "C:\devissetup\img\auturf.mhu"; DestDir: "{app}\devis"; Flags: ignoreversion 
Source: "C:\devissetup\img\*.mp3"; DestDir: "{app}\devis"; Flags: ignoreversion 
Source: "C:\devissetup\img\*.ico"; DestDir: "{app}\devis"; Flags: ignoreversion 
Source: "C:\devissetup\img\*.htm"; DestDir: "{app}\devis"; Flags: ignoreversion
Source: "C:\devissetup\img\*.htm"; DestDir: "{app}\offre"; Flags: ignoreversion
Source: "C:\devissetup\img\*.jpg"; DestDir: "{app}\devis"; Flags: ignoreversion
Source: "C:\devissetup\img\*.ini"; DestDir: "{app}"; Flags: onlyifdoesntexist

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]  
Root: HKCU; Subkey: "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; ValueType: string; ValueName: "c:\mhu\devismhu.exe"; ValueData: "~HIGHDPIAWARE"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; ValueType: string; ValueName: "c:\mhu\maintdevis.exe"; ValueData: "~HIGHDPIAWARE"; Flags: uninsdeletevalue


