; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!


#define MyAppName "DevisDEMO"
#define MyAppVersion "20.9.4.0"
#define MyAppPublisher "MHU"
#define MyAppURL "http://www.mhu.fr"
#define MyAppExeName "devisdemo.exe"
#define Mysetupname "devisdemo_20-9-4-0"



[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
PrivilegesRequired=lowest
AppId={{DAD3B999-9AF7-4880-ACB9-DCFB47E2EBE3}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
UsePreviousAppDir=no
DefaultDirName=c:\mhudev


DisableDirPage=yes
DefaultGroupName=devisdev
DisableProgramGroupPage=yes
WizardStyle=modern
DisableWelcomePage=no
OutputDir=C:\devisdemo
OutputBaseFilename={#Mysetupname}
SetupIconFile=C:\devissetup\boitetest.ico
Compression=lzma
SolidCompression=yes
WizardImageFile=c:\devissetup\imgsetup.bmp
WizardSmallImageFile=c:\devissetup\logomhu55.bmp

[Languages]
Name: "fr"; MessagesFile: "compiler:Languages\French.isl"

[Messages]
WelcomeLabel2= Cet assistant va procéder à la mise à jour de [name/ver]  sur votre ordinateur.

[Code]
procedure InitializeWizard();
begin
  WizardForm.WelcomeLabel2.Font.Style := [fsBold]; //Bold
  WizardForm.WelcomeLabel2.Font.Color := clnavy; // And red colour
end;

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";


[Dirs]
Name: "{app}\devis"
Name: "{app}\offre"
Name: "{app}\log"
Name: "{app}\exportdevis"

[Files]
;Source: "C:\mhu\printpdf\NotesdeVersion.pdf"; DestDir: "{app}"; Flags: isreadme

Source: "C:\devistest\Win32\Release\devisdemo.exe"; DestDir: "{app}"; Flags: ignoreversion
;Source: "C:\devismaint\Win32\Release\maintdevis.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\deviscim\Win32\Release\alerteheure.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\devissetup\*.dll"; DestDir: "{app}"; Flags: ignoreversion 

;Source: "C:\devissetup\tools\*.exe"; DestDir: "{app}"; Flags: ignoreversion 
;Source: "C:\devissetup\tools\*.txt"; DestDir: "{app}"; Flags: ignoreversion 
;Source: "C:\devissetup\tools\*.mhu"; DestDir: "{app}"; Flags: ignoreversion 

; Suite que si modif

;Source: "C:\devissetup\img\*.ani"; DestDir: "{app}\devis"; Flags: ignoreversion 
;Source: "C:\devissetup\img\*.frx"; DestDir: "{app}\devis"; Flags: ignoreversion 
;Source: "C:\devissetup\img\*.conf"; DestDir: "{app}\devis"; Flags: ignoreversion 
Source: "C:\devissetup\img\auturf.mhu"; DestDir: "{app}\devis"; Flags: ignoreversion 
;Source: "C:\devissetup\img\*.gif"; DestDir: "{app}\devis"; Flags: ignoreversion
Source: "C:\devissetup\img\*.ico"; DestDir: "{app}"; Flags: ignoreversion 
Source: "C:\devissetup\img\*.htm"; DestDir: "{app}\devis"; Flags: ignoreversion
;Source: "C:\devissetup\img\*.htm"; DestDir: "{app}\offre"; Flags: ignoreversion
;Source: "C:\devissetup\img\*.txt"; DestDir: "{app}\log"; Flags: ignoreversion
Source: "C:\devissetup\mhudemo\*.ini"; DestDir: "{app}"; Flags: onlyifdoesntexist

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]  
Root: HKCU; Subkey: "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; ValueType: string; ValueName: "c:\mhu\devisdemo.exe"; ValueData: "~HIGHDPIAWARE"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; ValueType: string; ValueName: "c:\mhu\maintdevis.exe"; ValueData: "~HIGHDPIAWARE"; Flags: uninsdeletevalue


